# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.3"

gem "cssbundling-rails"
gem "jbuilder"
gem "jsbundling-rails"
gem "postgresql"
gem "puma", ">= 5.0"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "graphql"
gem "discard", "~> 1.2"
gem "rack-cors"
gem "devise", "~> 4.9"

gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "factory_bot_rails"
  gem "ffaker"
  gem "rspec-rails"
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "standard"
  gem "standard-rails"
  gem "standard-performance"
  gem "web-console"
  gem "graphiql-rails"
  gem "meta_request"
end

group :test do
  # I use this for the validation matchers, and leave the rest of it alone.
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "simplecov-lcov", require: false
end
