source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.3"

gem "cssbundling-rails"
gem "jbuilder"
gem "jsbundling-rails"
gem "postgresql"
gem "puma", ">= 5.0"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "graphql"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-rails", '~> 6.1.0'
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "standard"
  gem "web-console"
end
gem "graphiql-rails", group: :development
